### ISSUE TITLE
Archive page isn't showing anything

### ISSUE THREAD

**Issue by deichcode** [redVi/voyager#3]
When I launch a clean copy of voyager theme with `jekyll serve` I got no error, but the archive page seems to be empty. This problem does not exists anymore when I change the permalink to something else then `/potsts/`. I do not know much about Jekyll but i think this has something to do with the `posts.html` in the root folder, that there is some kind of conflict.

**Comment by redVi** [comment]
Hi. I removed `posts.html`.  I suggest to use `archive.md` instead of it. You can set any permalink in this template. I have everything working well. Does that solve your problem?

**Comment by redVi** [comment]
Well, thanks for the issue! I think I can close it 1e5cf50037346c3ff2f392440011aae944b4f8eb
