### ISSUE TITLE
select images only in the content

### ISSUE THREAD

**Issue by redVi** [redVi/voyager#6]
@marcosni wrote [link](https://github.com/redVi/voyager/commit/80cb16b157ae16e42568f1deac3df1a2e0d95d7a#commitcomment-32675414)

**Comment by redVi** [comment]
@marcosni the problem is solved?

**Comment by marcosni** [comment]
Yes it did!! Thank you so much! I was thinking of (somehow) using the blog-logo class on the toggle script but your solution seems so much better!! It's my first time using Git and It's been way too long since I coded anything...

**Comment by redVi** [comment]
I was happy to help ;)
